### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by jianghuzai** [justauth/JustAuth#104]
建议对源码拆分多模块。一个模块只含有一种登录。
这样用户可以有针对性引用相应的依赖，而不需要一股脑所有的登录方式都引入了。

**Comment by zhangyd-c** [comment]
这块有做规划，不过不是对每一种登录进行拆分，而是按照类别，比如开发类、企业类、国外类这种

**Comment by zhangyd-c** [comment]
欢迎关注哈
