### ISSUE TITLE
请求linkedin时填写其他授权报错5008

### ISSUE THREAD

**Issue by yukmingyu** [justauth/JustAuth#108]
![image](https://user-images.githubusercontent.com/49110180/103276734-53211880-4a02-11eb-9178-d1fa0e8496a4.png)
![image](https://user-images.githubusercontent.com/49110180/103276761-69c76f80-4a02-11eb-955f-cff818dd6286.png)

目前已经有公司linkin主页，账号是主页管理员

![image](https://user-images.githubusercontent.com/49110180/103276877-a1361c00-4a02-11eb-8530-3c489fec708a.png)
这里的意思应该是账号登陆了app就会增加这些授权列表，目前还是只有3个，yml添加授权就会报5008

**Comment by xkcoding** [comment]
yml 新增的两项，估计是需要申请如图的 Product 才会有

![image](https://user-images.githubusercontent.com/10429917/103277132-494be500-4a03-11eb-8418-87ab624be24e.png)

由于我的还在审核中，后面审核通过，再跟进

**Comment by xkcoding** [comment]
经翻阅相关文档，确实需要申请 `Marketing Developer Platform` 才可以使用您列出来的 scopes
文档地址如下：https://docs.microsoft.com/zh-cn/linkedin/marketing/getting-started#how-do-i-access-marketing-apis

![image](https://user-images.githubusercontent.com/10429917/103336791-24fc1100-4ab4-11eb-99a3-9b571811dcee.png)

**Comment by yukmingyu** [comment]
好的谢谢,就是不用特意yml去配置了吗?只要申请好了justauth里会默认添加吗?

**Comment by xkcoding** [comment]
> 好的谢谢,就是不用特意yml去配置了吗?只要申请好了justauth里会默认添加吗?

不是的，是要先去申请，然后在 yml 里配置，JA 只是帮你集成，他不会帮你去设置
