### ISSUE TITLE
feat: 支持 “企业微信登录” 作为一个第三方登录的方案 

### ISSUE THREAD

**Issue by lovejoy** [justauth/JustAuth#111]
## Feature description

支持 “企业微信登录” 作为一个第三方登录的方案 

目前的企业微信登录看了文档，应该是用企业微信登录这个企业自己的网站

而不是用企业微信登录我的网站，不是个公共的方案

区别是应该是下面这个文档
https://open.work.weixin.qq.com/api/doc/90001/90143/91123

**Comment by zhangyd-c** [comment]
收到

**Comment by zhangyd-c** [comment]
https://justauth.wiki/oauth/wechat_enterprise_qrcode.html
https://justauth.wiki/oauth/wechat_enterprise_web.html

参考这两个文档

**Comment by zhangyd-c** [comment]
已解决。https://github.com/justauth/JustAuth/pull/127 稍后发布版本

**Comment by zhangyd-c** [comment]
https://github.com/justauth/JustAuth/releases/tag/v1.16.3 已发布
