### ISSUE TITLE
feat: LDAP

### ISSUE THREAD

**Issue by myoss** [justauth/JustAuth#112]
## Why did you add this feature?

LDAP

## Feature description

LDAP integration

**Comment by zhangyd-c** [comment]
请关注 JustAuthPlus 项目，该项目会集成 LDAP 
https://github.com/fujieid/jap
https://gitee.com/fujieid/jap

JustAuthPlus（以下简称"JAP"）是一款开源的登录认证中间件，基于模块化设计，为所有需要登录认证的 WEB 应用提供一套标准的技术解决方案，开发者可以基于 JAP 适配绝大多数的 WEB 系统（自有系统、联邦协议），就像集成 JustAuth 一样，简单方便。

![image](https://user-images.githubusercontent.com/12689082/115980542-1932de00-a5c0-11eb-960f-1257e40b7e6d.png)
