### ISSUE TITLE
request help:

### ISSUE THREAD

**Issue by YK-Leung** [justauth/JustAuth#121]
## Issue description
能否在authuser增加phone或者mobile字段？
## Environment
all
- JustAuth version(e.g. `1.15.1`):

**Comment by zhangyd-c** [comment]
phone 这个属性大部分平台都不返回，所以就没有单独定义字段。另外， AuthUser 中的 rawUserInfo 中是第三方返回的原始数据，如果你们需要，可以定制一部分解析器，解析这个字段获取 phone
