### ISSUE TITLE
请问支持双因素认证吗？

### ISSUE THREAD

**Issue by rujianwang** [justauth/JustAuth#123]
## Environment

- JustAuth version(e.g. `1.15.1`):

**Comment by zhangyd-c** [comment]
JustAuth 本身不支持双因素认证，第三方平台是否支持需要看具体情况，谢谢。

另外，https://gitee.com/fujieid/jap 这个项目中有 MFA 插件，可以试一下。

参考文档：https://justauth.plus/quickstart/jap-mfa.html
