### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by fu3655** [justauth/JustAuth#124]
有没有交流群什么的呢？里面的第三方登录支持自定义吗？不是很想放很多个在上面。

**Comment by zhangyd-c** [comment]
https://justauth.wiki/features/customize-the-oauth.html

**Comment by zhangyd-c** [comment]
![image](https://user-images.githubusercontent.com/12689082/127085280-74baab2d-83f7-4940-aca7-66a872bad911.png)
