### ISSUE TITLE
bug:facebook登录输入用户名密码后报错

### ISSUE THREAD

**Issue by caoyixian** [justauth/JustAuth#135]
<img width="873" alt="1630718557" src="https://user-images.githubusercontent.com/32952080/132077810-39438a4e-ec04-4121-8327-557ed7242a26.png">

**Comment by zhangyd-c** [comment]
你传递了没有权限的scope，在声明 AuthRequest 时，可以先把 scopes 的配置去掉，使用默认的 scope
