### ISSUE TITLE
bug:JDK11早先版本中，如果自定义Http Header会抛异常，并且请求失败。

### ISSUE THREAD

**Issue by cheng521521** [justauth/JustAuth#156]
## Issue description
![image](https://user-images.githubusercontent.com/53562490/189637523-7395f30e-ebec-4a90-aecd-bd58557da2d5.png)

![image](https://user-images.githubusercontent.com/53562490/189637572-7f99db48-c7bd-4261-97d3-b0f892c2948f.png)

## Environment
- JustAuth version(e.g. `1.16.5`): 

### stackoverflow的链接
https://stackoverflow.com/questions/52315472/how-to-customise-host-header-in-java-http-client

解决方法是夹JDK启动参数，但是我觉得这种方式不优雅。不知道有什么好的解决方案吗。

**Comment by chenchensheng** [comment]
在项目启动时可以通过 `HttpUtil.setHttp()` 方法指定具体的 Http 实现类 (需要导入对应的库) 而不使用 JDK 自带的 `HttpClient` 

``` java
HttpUtil.setHttp(new HutoolImpl());
// 或 HttpUtil.setHttp(new OkHttp3Impl());
```

**Comment by cheng521521** [comment]
好的，非常感谢。：）
