### ISSUE TITLE
feat: 微信开放平台只支持网站应用的吗？有没有考虑支持移动应用呢？

### ISSUE THREAD

**Issue by LiJun990105** [justauth/JustAuth#173]

**Comment by zhangyd-c** [comment]
开放平台和移动端微信认证理论上通用。参考：https://justauth.cn/guide/oauth/wechat_open/#_2-2-%E5%88%9B%E5%BB%BArequest

在实际使用中，移动端 APP 拉起微信应用进行授权，授权完成后一样会颁发一个 code。然后使用这个 code 封装为 `AuthCallback` 后调用 `authRequest.login(callback);` 即可。

这种情况下，注意在 `AuthConfig` 中需要指定 `ignoreCheckState=true`
