### ISSUE TITLE
feat: 能否支持公众号二维码关注后进行登录注册的功能

### ISSUE THREAD

**Issue by Hzrr97** [justauth/JustAuth#196]
## Why did you add this feature?
我需要通过扫码关注公众号后进行登录注册，看了下微信开放平台的文档，貌似都是静默登录，没有关注公众号的操作。

**Comment by ion1ze** [comment]
这个直接用消息通知做就行了，关注事件，网上很多例子，不是走的官方的 OAuth2 接口

**Comment by Hzrr97** [comment]
好的
