### ISSUE TITLE
对方案的理解有点问题，想请教～

### ISSUE THREAD

**Issue by dustturtle** [justauth/JustAuth#39]
我是一名客户端开发者，我们做app时经常会集成第三方的sdk来实现第三方登陆。 我看这个库是服务端的实现吧，具体的应用场景是在哪儿啊？ 是网页？涉及不涉及原生app的接口调用？
谢谢了！🙏

**Comment by zhangyd-c** [comment]
@Xarrow 理解的对。JustAuth就是web端的授权登录，不支持app应用

**Comment by dustturtle** [comment]
理解了，多谢讲解！
