### ISSUE TITLE
feature request: gitlab支持

### ISSUE THREAD

**Issue by zaoqi** [justauth/JustAuth#43]

**Comment by zhangyd-c** [comment]
![image](https://user-images.githubusercontent.com/12689082/64303595-72996400-cfbb-11e9-9a76-b1e84acadb18.png)

https://github.com/justauth/JustAuth/releases/tag/v1.11.0

请更新依赖版本：

```
<dependency>
  <groupId>me.zhyd.oauth</groupId>
  <artifactId>JustAuth</artifactId>
  <version>1.11.0</version>
</dependency>
```

Gitlab：https://gitlab.com
