### ISSUE TITLE
app接口后台授权问题

### ISSUE THREAD

**Issue by JJS857012499** [justauth/JustAuth#46]
app授权后拿到的是openId，如果app这边传递过来是type和openId
后台根据type从对应第三方验证openId是否合法已经获取用户的基本信息。
是否能添加进这些功能

**Comment by zhangyd-c** [comment]
已经登录过的用户，信息应该已经保存下来了，包括type和openid。 你们app传过来的openid，你不可以直接去库里查吗？

**Comment by JJS857012499** [comment]
> 已经登录过的用户，信息应该已经保存下来了，包括type和openid。 你们app传过来的openid，你不可以直接去库里查吗？

我意思是说在是客户端集成sdk，不在后台做授权回调，客户端传递到后台是openId+type，如果是第一次，库是没有这个openId记录的，后台需要根据openId+appkey+secretKey去第三方api获取用户信息

**Comment by sendtion** [comment]
android可以使用这个库吗

**Comment by JJS857012499** [comment]
> android可以使用这个库吗

不建议用，这个本来是给后台用的，安卓应该用share sdk这些，毕竟secretKey等敏感信息不应该暴露在前端

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：Sendtion <notifications@github.com>
发送时间：2020-01-12 09:59
主题：Re: [justauth/JustAuth] app接口后台授权问题 (#46)
收件人："justauth/JustAuth"<JustAuth@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

android可以使用这个库吗
