### ISSUE TITLE
关于扩展

### ISSUE THREAD

**Issue by zj-dreamly** [justauth/JustAuth#47]
您好，公司内部用的明道云，justAuth没有集成，我参照gitee的实现，继承了AuthDefaultRequest，发现要传入的AuthSource是枚举，里面是定义好的，没法自己去实现呀

**Comment by zhangyd-c** [comment]
您好，**明道云**我们尽快集成进去，后面JustAuth会进行一次升级，支持使用者自定义api链接和自定义实现oauth流程。

**Comment by zj-dreamly** [comment]
好的，感谢

**Comment by zhangyd-c** [comment]
@zj-dreamly 最新版（v1.12.0）已经支持自定义实现第三方OAuth了

**Comment by zj-dreamly** [comment]
好的，谢谢

**Comment by mwxxhdb** [comment]
> @zj-dreamly 最新版（v1.12.0）已经支持自定义实现第三方OAuth了，欢迎试用

自己搭建 gitlab，为什么不能只定义 source，使用自带的 AuthGitlabRequest 呢。
