### ISSUE TITLE
github auth 需要增加 scope

### ISSUE THREAD

**Issue by li24361** [justauth/JustAuth#50]
很多授权需要读取org的信息, 现在只能手动拼上,效率比较低

**Comment by zhangyd-c** [comment]
我看了几家的第三方登录（oschina、b3log、gitee），都没有在登录的时候获取其他scope信息的，JustAuth作为授权登录的工具，目前只提供获取用户基本信息的权限，其他权限你可以先自己手动获取。后期我们再考虑一下是否要加入这个功能。
感谢您的支持！
