### ISSUE TITLE
AuthCallback在spring中接收参数异常，需要有默认的构造方法

### ISSUE THREAD

**Issue by jnan88** [justauth/JustAuth#52]
AuthCallback需要添加注解

@NoArgsConstructor
@AllArgsConstructor

**Comment by bestsort** [comment]
翻了一下 commit 记录，AuthCallback 的这个`@Builder`注解是在1.13.0(spring-boot-start版本1.3.0)新加入的。没修复这个bug之前可以先用1.12.0

**Comment by zhangyd-c** [comment]
https://github.com/justauth/JustAuth/pull/54 这个问题已经修复， 将在今天晚发布1.30.1版本，到时候会再通知你哈。

**Comment by xkcoding** [comment]
starter 也同步修复了，版本号为 `1.3.1`

**Comment by liaozan** [comment]
@xkcoding 可以考虑把starter的源码一起发布一下

**Comment by zhangyd-c** [comment]
> @xkcoding 可以考虑把starter的源码一起发布一下
已经更新了哦 https://github.com/justauth/justauth-spring-boot-starter

**Comment by liaozan** [comment]
> @xkcoding 可以考虑把starter的源码一起发布一下
> 已经更新了哦 https://github.com/justauth/justauth-spring-boot-starter

我的意思是starter的源代码打包到Maven仓库😂

**Comment by zhangyd-c** [comment]
> > @xkcoding 可以考虑把starter的源码一起发布一下
> > 已经更新了哦 https://github.com/justauth/justauth-spring-boot-starter
> 
> 我的意思是starter的源代码打包到Maven仓库😂

有啊，都发布了。 https://search.maven.org/search?q=justauth-spring-boot-starter 这儿可以看到

**Comment by liaozan** [comment]
> > > @xkcoding 可以考虑把starter的源码一起发布一下
> > > 已经更新了哦 https://github.com/justauth/justauth-spring-boot-starter
> > 
> > 
> > 我的意思是starter的源代码打包到Maven仓库😂
> 
> 有啊，都发布了。 https://search.maven.org/search?q=justauth-spring-boot-starter 这儿可以看到

sorry。。估计是昨天更新之后家里电脑没拉到，今天到公司拉到源码了
