### ISSUE TITLE
钉钉登录建议：在返回的AuthUser设置 dingId。

### ISSUE THREAD

**Issue by hongliming** [justauth/JustAuth#58]
钉钉登录返回的信息可能包含：

{"user_info":{"dingId":"xxx","nick":"xxx","unionid":"xxx","openid":"xx"},"errmsg":"ok","errcode":0}

建议在可以优先使用dingId，企业应用可以减少绑定操作。谢谢

**Comment by zhangyd-c** [comment]
收到，感谢反馈

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人："yadong.zhang" <notifications@github.com>
发送时间：2020-01-02 14:12
主题：Re: [justauth/JustAuth] 钉钉登录建议：在返回的AuthUser设置 dingId。 (#58)
收件人："justauth/JustAuth"<JustAuth@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

收到，感谢反馈
