### ISSUE TITLE
请问是否可以通过clientId,clientSecret,redirectUri查询淘宝订单？

### ISSUE THREAD

**Issue by focusme** [justauth/JustAuth#62]
如题，谢谢

**Comment by focusme** [comment]
查询速卖通卖家订单

**Comment by zhangyd-c** [comment]
这个需要你去查询下淘宝相关的API介绍。JustAuth只做授权登录用

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：focusme <notifications@github.com>
发送时间：2019-12-31 10:32
主题：Re: [justauth/JustAuth] 请问是否可以通过clientId,clientSecret,redirectUri查询淘宝订单？ (#62)
收件人："justauth/JustAuth"<JustAuth@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

查询速卖通卖家订单
