### ISSUE TITLE
支持京东吗，能不能扩展下

### ISSUE THREAD

**Issue by aaronyin** [justauth/JustAuth#67]
支持京东吗，能不能扩展下

**Comment by zhangyd-c** [comment]
京东的开发完了，还没有合并。 合并完会通知您。感谢支持

**Comment by zhangyd-c** [comment]
另外方便留下联系方式吗？如果可以，请发到：yadong.zhang0415#gmail.com

**Comment by zhangyd-c** [comment]
sorry， 之前忘了通知你了。 https://gitee.com/yadong.zhang/JustAuth/releases/v.1.15.1 京东的已经支持了
