### ISSUE TITLE
如何给HttpRequest设置proxy

### ISSUE THREAD

**Issue by ICLXL** [justauth/JustAuth#75]

**Comment by zlf2002171** [comment]
unsubscribe

2020-05-18 

zlf2002171 



发件人：ICLXL <notifications@github.com>
发送时间：2020-05-11 15:26
主题：[justauth/JustAuth] 如何给HttpRequest设置proxy (#75)
收件人："justauth/JustAuth"<JustAuth@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

**Comment by zhangyd-c** [comment]
这一版暂时不支持给 Http 设置 proxy，如果想使用代理，只能设置全局代理， 下一版本会加上该功能。

另外，可以关注我的公众号： `码一码（zhyd0415）`，最新动态都会通过我的公众号在第一时间发布

**Comment by zhangyd-c** [comment]
新版已发布，请升级。版本更新内容：https://github.com/justauth/JustAuth/releases/tag/1.15.5
```
<dependency>
    <groupId>me.zhyd.oauth</groupId>
    <artifactId>JustAuth</artifactId>
    <version>1.15.5</version>
</dependency>
```
