### ISSUE TITLE
你们好，想问下为什么我使用百度登录的方式，获取不到用户id呢？github和gitee都正常

### ISSUE THREAD

**Issue by 873310466** [justauth/JustAuth#80]
百度
![百度](https://typora-imgzc.oss-cn-beijing.aliyuncs.com/typora_img/20200525230239.png)

码云
![](https://typora-imgzc.oss-cn-beijing.aliyuncs.com/typora_img/20200525230543.png)

**Comment by zhangyd-c** [comment]
新版已发布，请升级
```
<dependency>
    <groupId>me.zhyd.oauth</groupId>
    <artifactId>JustAuth</artifactId>
    <version>1.15.5</version>
</dependency>
```
