### ISSUE TITLE
第三方回调的时候,是不是可以增加以下不需要state的一种需求,现在AuthChecker.checkState(authCallback.getState(), source, authStateCache);这一步卡的死死的,建议增加一个判断state值是否存在在请求该方法

### ISSUE THREAD

**Issue by G-H-Tao** [justauth/JustAuth#83]

**Comment by zhangyd-c** [comment]
state如果不传，默认会生成一个uuid
![image](https://user-images.githubusercontent.com/12689082/83964126-11e9df80-a8dd-11ea-89a8-11fb947151cf.png)
因此应该不会出现你说的这种情况啊， 方便详细描述一下吗

**Comment by yuenke** [comment]
> state如果不传，默认会生成一个uuid
> ![image](https://user-images.githubusercontent.com/12689082/83964126-11e9df80-a8dd-11ea-89a8-11fb947151cf.png)
> 因此应该不会出现你说的这种情况啊， 方便详细描述一下吗

他可能说的是默认的login方法，里面校验了的state值，会判断缓存。
![image](https://user-images.githubusercontent.com/20986198/84490629-01b77300-acd6-11ea-962e-e89308f7a929.png)
我也遇到这个问题了，不过我把这个方法重写了，去掉了这个校验。
建议可以加个重载方法之类的。

**Comment by G-H-Tao** [comment]
正是二楼说的这样,请求默认的login方法的时候校验的state值.因为我的这边获取微信登录二维码的时候是前端直接请求微信接口获取二维码的,state值是前台赋值并校验的,我这边只需要通过前台给我的code值解析用户信息就行了,但是请求这个默认的登录后台没有state的缓存值,一直报错.
`@Override
    public AuthResponse login(AuthCallback authCallback) {
        try {
            AuthChecker.checkCode(source, authCallback);
            AuthChecker.checkState(authCallback.getState(), source, authStateCache);

            AuthToken authToken = this.getAccessToken(authCallback);
            AuthUser user = this.getUserInfo(authToken);
            return AuthResponse.builder().code(AuthResponseStatus.SUCCESS.getCode()).data(user).build();
        } catch (Exception e) {
            Log.error("Failed to login with oauth authorization.", e);
            return this.responseError(e);
        }
    }`

**Comment by zhangyd-c** [comment]
新版已发布，参考：https://github.com/justauth/JustAuth/releases/tag/1.15.6
![image](https://user-images.githubusercontent.com/12689082/86103667-a2d46500-baef-11ea-8a7b-7eca7f9ebcdb.png)

**Comment by zhangyd-c** [comment]
现在maven仓库中可能还没同步，1~2小时后应该就同步过来了

**Comment by liu-yanbo** [comment]
生产环境（阿里云主机）出现这个问题，但是测试环境没有（本地私有云），不知怎么排查。
