### ISSUE TITLE
feat: update Github authorization

### ISSUE THREAD

**Issue by wangyonghong** [justauth/JustAuth#89]
## Why did you add this feature?

I got an email from Github:

Hi @wangyonghong,

On September 1st, 2020 at 01:44 (UTC) your application (OAuth local) used an access token (with the User-Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 simple-http) as part of a query parameter to access an endpoint through the GitHub API:

https://api.github.com/user

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

Depending on your API usage, we'll be sending you this email reminder on a monthly basis.

Visit https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param for more information about suggested workarounds and removal dates.

Thanks,
The GitHub Team

## Feature description

Please use the Authorization HTTP header instead as using the `access_token` query parameter is deprecated.

**Comment by zhangyd-c** [comment]
Please use the latest version. https://github.com/justauth/JustAuth/releases
