### ISSUE TITLE
请问出现这两个错误是什么原因？

### ISSUE THREAD

**Issue by WZLSS** [justauth/JustAuth#90]
## Issue description
me.zhyd.oauth.exception.AuthException: The code passed is incorrect or expired.

com.xkcoding.http.exception.SimpleHttpException: java.net.SocketException: Connection reset
## Environment

- JustAuth version(1.15.7-beta.3)
- hutool-http(5.2.5)
- jdk(1.8)

**Comment by zhangyd-c** [comment]
哪个平台的

**Comment by WZLSS** [comment]
GitHub

**Comment by zhangyd-c** [comment]
Github 目前需要 科学上网。 参考 https://justauth.wiki/#/oauth/google

AuthConfig 中需要配置 `httpConfig`
