### ISSUE TITLE
Twitter's request_token api no need redirect_uri，i took off some code about redirect_uri check and it worked.

### ISSUE THREAD

**Issue by zhangzewa** [justauth/JustAuth#92]
I will suggest AuthTwitterRequest.java no need to check the redirect_uri in next realese version
like the code down here:
`AuthDefaultRequest#AuthDefaultRequest
        if (!AuthChecker.isSupportedAuth(config, source)) {
            throw new AuthException(AuthResponseStatus.PARAMETER_INCOMPLETE, source);
        }
        // 校验配置合法性
        AuthChecker.checkConfig(config, source);`

**Comment by zhangzewa** [comment]
推特的request_token不需要redirect_uri的校验，我注释掉参数校验的代码，就能正常工作了。

**Comment by GuryYu** [comment]
同样遇到了这个问题

目前我将JustAuth用在了微信APP登录。
微信APP登录使用的参数和现有的AuthWeChatOpenRequest是一致的，但是在APP登录时不需要传redirect_uri参数。
当前版本的JustAuth强制验证了redirect_uri必须传，手动修改代码解除限制后，APP登录的功能一切正常。

大多数的第三方APP登录不需要传递redirect_uri参数，希望能够给与一个配置或config参数来标识某种登录方式是否需要验证redirect_uri参数。

**Comment by zhangyd-c** [comment]
1.16.1已发布，请注意升级。https://github.com/justauth/JustAuth/releases/tag/v1.16.1
