### ISSUE TITLE
集成gitee/github登录报错：Has no HttpImpl defined in environment!

### ISSUE THREAD

**Issue by Miazzy** [justauth/JustAuth#93]
报错：Has no HttpImpl defined in environment!

![截屏2020-09-19 18 49 19](https://user-images.githubusercontent.com/18606977/93665410-d698a880-faa8-11ea-9c87-2a710401915a.png)

![截屏2020-09-19 18 49 36](https://user-images.githubusercontent.com/18606977/93665415-df897a00-faa8-11ea-9a93-3785d42074be.png)

![截屏2020-09-19 18 49 51](https://user-images.githubusercontent.com/18606977/93665419-e87a4b80-faa8-11ea-8d05-d78c73c5c996.png)

**Comment by snaigle** [comment]
该库中默认没有http实现类，需要自行添加httpclient, hutool,okhttp3 等任一依赖类 ， 文档中有说明

**Comment by zhanpengguo** [comment]
我使用的是JustAuth-demo，里面添加了hutool-http，还是一直报错：Has no HttpImpl defined in environment!
使用的百度登录和开源中国登录，都是报这个错

**Comment by zhanpengguo** [comment]
JustAuth-demo里少了simple-http依赖，加上就好了
