### ISSUE TITLE
您好，能支持微软国内版吗？世纪互联的

### ISSUE THREAD

**Issue by hiarno** [justauth/JustAuth#97]
如题。

**Comment by zhangyd-c** [comment]
没理解您的意思，微软应该是通用的吧， 参考文档：https://docs.microsoft.com/zh-cn/graph/auth-v2-user

**Comment by hiarno** [comment]
根据我的实际使用情况是这样的，必须采用如下地址。
世纪互联的授权地址是不一样的。

https://login.chinacloudapi.cn/XXXXXXX/oauth2/v2.0/authorize
https://login.chinacloudapi.cn/XXXXXXX/oauth2/v2.0/token
https://microsoftgraph.chinacloudapi.cn/v1.0/me

**Comment by zhangyd-c** [comment]
done. 等新版发布 1.16.4
