### ISSUE TITLE
Bug: [转自邮件] 微信登录扫码报错

### ISSUE THREAD

**Issue by pengisgood** [justauth/JustAuth#99]
以下内容来自邮件（244277971 <244277971@qq.com>  Sat, Oct 31, 2020 at 7:01 PM）：

使用justAuth（Version：**1.15.8**）时，正常情况下测试没有问题；当使用内网穿透时，在微信登录扫码页面，扫码后报错：
```
2020-10-31 18:53:00 http-nio-9503-exec-1 me.zhyd.oauth.log.Log(error:45) [ERROR] - Failed to login with oauth authorization.me.zhyd.oauth.exception.AuthException: Illegal state [WECHAT_OPEN]	
at me.zhyd.oauth.utils.AuthChecker.checkState(AuthChecker.java:110)	
at me.zhyd.oauth.request.AuthDefaultRequest.login(AuthDefaultRequest.java:77)

打印核心日志： authResponse : {"msg":"Illegal state [WECHAT_OPEN]","code":5009}
```
此问题发现有很多人遇到过，参考：https://blog.csdn.net/yan50050/article/details/79654700

解决办法：在[`AuthWeChatMpRequest.java` 第128行](https://github.com/justauth/JustAuth/blob/abbfb733377a41dfb347f3a2ec63d5eaa9e654fa/src/main/java/me/zhyd/oauth/request/AuthWeChatMpRequest.java#L128)加上如下     
```
.queryParam("state", getRealState(state).concat("&connect_redirect=1#wechat_redirect"))
```
![image](https://user-images.githubusercontent.com/2988765/97795874-9bac9780-1c46-11eb-817a-b840a82720ca.png)

麻烦解决一下，大神们可以加上打个测试jar发我，然后我在本地测试一下看看是否确实可以解决，谢谢（maven 打包上传到库不太熟悉，希望大神帮个忙哈！）

**Comment by pengisgood** [comment]
@xkcoding Can you have a look at this issue?

**Comment by xkcoding** [comment]
@pengisgood 我微信过期了，暂时无法测试，我打了个 SNAPSHOT 包，邮件已经私发那个朋友了，后面 @zhangyd-c 发布一下 SNAPSHOT

**Comment by zhangyd-c** [comment]
please refer to [illegal-state-xx](https://justauth.wiki/#/qa/error?id=illegal-state-xx)

**Comment by zhangyd-c** [comment]
![Uploading image.png…]()

**Comment by mxsky** [comment]
感谢作者帮忙，已经定位到问题，是由于没有使用redis统一缓存state参数，用的是内存缓存，发布在外网的程序生成的state，在回调时穿透到内网本地程序检验state错误导致的；不需要改动源代码，我加了个redis扩展缓存解决了！
还是要感谢一下作者，建议在state检验异常时，加个提示：Illegal state  or check you state in one cache !
